FichaAcademia/FichaAcademia/Models/ErrorViewModel.cs
using System;

namespace FichaAcademia.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FichaAcademia/FichaAcademia/ViewModels/AdministradorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FichaAcademia.ViewModels
{
    public class AdministradorViewModel
    {
        [Required(ErrorMessage = "Campo obrigatório")]
        [EmailAddress(ErrorMessage = "Email inválido")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }
}

FichaAcademia/FichaAcademia/Controllers/AdministradoresController.cs
using FichaAcademia.AcessoDados.Interfaces;
using FichaAcademia.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FichaAcademia.Controllers
{
    public class AdministradoresController : Controller
    {
        private readonly IAdministradorRepositorio _administradorRepositorio;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AdministradoresController(IAdministradorRepositorio administradorRepositorio, IHttpContextAccessor httpContextAccessor)
        {
            _administradorRepositorio = administradorRepositorio;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated) // Limpa as sessoes
            {
                HttpContext.SignOutAsync(); //Desloga
                HttpContext.Session.Clear(); //Limpa a sessao
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(AdministradorViewModel administradorViewModel)
        {
            //Se nao existe
            if(! _administradorRepositorio.AdministradorExiste(administradorViewModel.Email, administradorViewModel.Senha))
            {
                ModelState.AddModelError(string.Empty, "Email e/ou senha inválido!");
                return View(administradorViewModel);
            }

            //Loga o usuario
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, administradorViewModel.Email)
            };

            var userIdentity = new ClaimsIdentity(claims, "login");

            ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
            await HttpContext.SignInAsync(principal);

            //Armazenar email em uma sessao
            HttpContext.Session.SetString("Usuario", administradorViewModel.Email);

            ViewData["Usuario"] = HttpContext.Session.GetString("Usuario");

            return RedirectToAction("Index", "Alunos");
        }

        public async Task<IActionResult> Logout()
        {
            //Desloga e redireciona para a pagina de Login
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

FichaAcademia/FichaAcademia/Controllers/CategoriasExerciciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FichaAcademia.AcessoDados;
using FichaAcademia.Dominio.Models;
using FichaAcademia.AcessoDados.Interfaces;

namespace FichaAcademia.Controllers
{
    public class CategoriasExerciciosController : Controller
    {
        private readonly ICategoriaExercicioRepositorio _categoriaExercicioRepositorio;

        public CategoriasExerciciosController(ICategoriaExercicioRepositorio categoriaExercicioRepositorio)
        {
            _categoriaExercicioRepositorio = categoriaExercicioRepositorio;
        }

        // GET: CategoriasExercicios
        public async Task<IActionResult> Index()
        {
            return View(_categoriaExercicioRepositorio.PegarTodos());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoriaExercicioId,Nome")] CategoriaExercicio categoriaExercicio)
        {
            if (ModelState.IsValid)
            {
                await _categoriaExercicioRepositorio.Inserir(categoriaExercicio);
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaExercicio);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaExercicio = await _categoriaExercicioRepositorio.PegarPeloId(id);
            if (categoriaExercicio == null)
            {
                return NotFound();
            }
            return View(categoriaExercicio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoriaExercicioId,Nome")] CategoriaExercicio categoriaExercicio)
        {
            if (id != categoriaExercicio.CategoriaExercicioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _categoriaExercicioRepositorio.Atualizar(categoriaExercicio);
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaExercicio);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _categoriaExercicioRepositorio.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<JsonResult> CategoriaExiste(string nome, int CategoriaExercicioId)
        {
            if(CategoriaExercicioId == 0) //Esta criando um novo
            {
                if (await _categoriaExercicioRepositorio.CategoriaExiste(nome))
                    return Json("Categoria já existe");

                return Json(true);
            }
            else //Atualização
            {
                if (await _categoriaExercicioRepositorio.CategoriaExiste(nome, CategoriaExercicioId))
                    return Json("Categoria já existe");

                return Json(true);
            }
        }
    }
}

FichaAcademia/FichaAcademia/Controllers/HomeController.cs
using FichaAcademia.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FichaAcademia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FichaAcademia/FichaAcademia/Views/Administradores/Login.cshtml
@model FichaAcademia.ViewModels.AdministradorViewModel

@{
    ViewData["Title"] = "Faça seu Login";
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <h6 class="collection-header">Efetue seu Login</h6>
                <form asp-action="Login">
                    <div class="collection-item">
                        <div asp-validation-summary="ModelOnly" class="red-text text-danger"></div>
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Email" class="validate" id="Email" />
                                <label for="Email">Email</label>
                                <span asp-validation-for="Email" class="red-text darken-3"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Senha" class="validate" id="Senha" />
                                <label for="Senha">Senha</label>
                                <span asp-validation-for="Senha" class="red-text darken-3"></span>
                            </div>
                        </div>
                        <div class="collection-item">
                            <input type="submit" value="Salvar" class="btn-small teal darken-2" /> &nbsp;
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FichaAcademia/FichaAcademia/Views/CategoriasExercicios/Create.cshtml
@model FichaAcademia.Dominio.Models.CategoriaExercicio

@{
    ViewData["Title"] = "Nova Categoria";
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <h6 class="collection-header">Nova categoria de exercicio</h6>
                <form asp-action="Create">
                    <div class="collection-item">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Nome" class="validate" id="Nome" />
                                <label for="Nome">Nome</label>
                                <span asp-validation-for="Nome" class="red-text darken-3"></span>
                            </div>
                        </div>
                        <div class="collection-item">
                            <input type="submit" value="Salvar" class="btn-small teal darken-3" /> &nbsp;
                            <a asp-action="Index" class="btn-small grey darken-1">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FichaAcademia/FichaAcademia/Views/CategoriasExercicios/Edit.cshtml
@model FichaAcademia.Dominio.Models.CategoriaExercicio

@{
    ViewData["Title"] = "Atualizar" + Model.Nome;
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <h6 class="collection-header">Atualizar @Model.Nome</h6>
                <form asp-action="Edit">
                    <div class="collection-item">
                        <input type="hidden" asp-for="CategoriaExercicioId" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Nome" class="validate" id="Nome" />
                                <label for="Nome">Nome</label>
                                <span asp-validation-for="Nome" class="red-text darken-3"></span>
                            </div>
                        </div>
                        <div class="collection-item">
                            <input type="submit" value="Salvar" class="btn-small teal darken-3" /> &nbsp;
                            <a asp-action="Index" class="btn-small grey darken-1">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FichaAcademia/FichaAcademia/Views/CategoriasExercicios/Index.cshtml
@model IEnumerable<FichaAcademia.Dominio.Models.CategoriaExercicio>

@{
    ViewData["Title"] = "Categorias de Exercicios";
}

<h1>Categoria de Exercicios</h1>

<p>
    <a asp-action="Create" class="btn-small green darken-2">Nova categoria</a>
</p>

<table class="table table-striped hover highlight">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CategoriaExercicioId" class="btn-small light-blue darken-2">Atualizar</a> &nbsp;
                    <a onclick="ExibirModal(@item.CategoriaExercicioId, '@item.Nome')" class="btn-small red darken-2">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal Exclusão -->
<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Confirmar exclusão</h4>
        <p>Deseja confirmar exclusão de <b class="nome"></b> ?</p>
    </div>
    <div class="modal-footer">
        <a class="modal-close btn red accent-4">Não</a>
        <a class="modal-close btn green accent-4 btnConfirmar">Sim</a>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.modal').modal();
        });

        function ExibirModal(id, nome) {
            $('.nome').html(nome);

            $('#modal1').modal('open');

            $('.btnConfirmar').on('click', function () {
                $.ajax({
                    method: 'POST',
                    url: '/CategoriasExercicios/Delete',
                    data: { id: id },
                    success: function () {
                        location.reload();
                    }
                });
            });

        }

    </script>
}

FichaAcademia/FichaAcademia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FichaAcademia/FichaAcademia/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAcessor

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FichaAcademia</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo">Logo</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Administradores" asp-action="Login">Login</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Objetivos" asp-action="Index">Objetivos</a></li>
                        <li><a asp-controller="Exercicios" asp-action="Index">Exercicios</a></li>
                        <li><a asp-controller="CategoriaExercicios" asp-action="Index">Categoria</a></li>
                        <li><a asp-controller="Professores" asp-action="Index">Professores</a></li>
                        <li><a asp-controller="Alunos" asp-action="Index">Alunos</a></li>
                        <li>Bem vindo, @HttpContextAcessor.HttpContext.Session.GetString("Usuario")</li>
                        <li><a asp-controller="Administradores" asp-action="Logout">Logout</a></li>
                    }

                </ul>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FichaAcademia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>